name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Custom Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build, tag and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          provenance: false
          push: true
          tags: |
            ghcr.io/${{ secrets.REGISTRY_USERNAME }}/${{ github.event.repository.name }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
